### ISSUE TITLE
New model for service authorization

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#123]
We need to fully support JWT authorization from Shipcat instead of the Kong OAuth 2 plugin.

This is going to be using multiple plugins, the [Kong JWT plugin](https://docs.konghq.com/hub/kong-inc/jwt/) for basic validation (signature/expiry) and a custom plugin to perform additional validation (Audience, scope and region validation).

The `authorization` configuration will be part of the Kong configuration, but could be added to other service proxies (e.g., Envoy in a service mesh or Gate)

# Examples
Some examples of common use cases for services.

## Global/regional defaults
```yaml
# shipcat.conf
defaults:
    kong:
        # Secure by default
        authorization:
            enabled: true
            configuration: "{{ base_urls.services }}/.well-known/openid-configuration"
            legacy: false
            allowed_audiences:
            - https://babylonhealth.com/
            allow_anonymous: false
            remove_invalid_tokens: true
regions:
- name: ops-cluster
  kong:
    auth: none
    authorization:
      enabled: false
- name: dev-uk
  kong:
    auth: enabled
# prod-uk hasn't been migrated to use the new authorization, so uses oauth2 instead
- name: prod-uk
  kong:
    auth: oauth2
    authorization:
        enabled: false
    
```

## Simple service
```yaml
# shipcat.yml
kong:
    uri: ...
    ## The defaults are fine

# staging.yml
kong:
    authorization:
        legacy: true
```

Most services should need no custom configuration. Invalid/anonymous requests won't reach them.

Older versions of the service may not understand JWTs (e.g., the one deployed to `staging`), so will require the `legacy` mode.

## Service with anonymous access
```yaml
# shipcat.yml
kong:
    authorization:
        allow_anonymous: true
```

Some services (e.g., privacy service) will accept requests with no `Authorization` token and will add an `Babylon-Anonymous: true` header.

Requests with invalid/expired access tokens will have the `Authorization` header removed, to prevent programming bugs in the services from causing invalid tokens to be trusted.

## Service allowing non-standard tokens
```yaml
# shipcat.yml
kong:
    authorization:
        allow_anonymous: true
        remove_invalid_tokens: false
```

Some services may receive non standard tokens/`Authorization` headers (e.g., if they receive Slack webhooks). With the above configuration, the `Authorization` header will not be removed (but an `Babylon-Anonymous: true` will be added).

## Services with specific scope
```yaml
# shipcat.yml
kong:
    authorization:
        required_scopes: [clinical]
```

## Services supporting cookies
```yaml
# shipcat.yml
kong:
    authorization:
        cookies: true
```

Services which are called by web applications may recieve the access token in cookies.

With the above configuration, the access token will be extracted from the `Authorization` header (if present) and CSRF protection will be enabled.

## Services with no authorization
```yaml
# shipcat.yml
kong:
    authorization:
        enabled: false
```

A service may want to fully disable Kong-level authorization. This should be quite rare, with `allow_anonymous: true` covering most use cases for `auth: none` (without the risk of programming errors introducing security bugs).

# Structure
On a resolved manifest, the schema will be as follows:

```rust
pub struct Kong {
    /// ...

    /// If present, Kong is configured to perform authorization for the service
    /// If omitted, no authorization is performed
    pub authorization: Option<Authorization>,
}

pub struct Authorization {
    /// OpenID Connect Discovery URL (for discovery of JWT public keys from the JWKS URL)
    ///
    /// e.g., https://login.microsoftonline.com/babylonpartners.onmicrosoft.com/v2.0/.well-known/openid-configuration or https://janslow-babylon.eu.auth0.com/.well-known/openid-configuration
    pub configuration: String,
    
    /// Add legacy headers
    ///
    /// Add Kong OAuth 2.0 style legacy headers, e.g., `X-Authenticated-Userid` for services which aren't aware of JWTs
    pub legacy: bool,

    /// Allowed values for the `aud` claim of the JWT payload.
    pub allowed_audiences: Vec<String>,

    /// Are anonymous requests allowed to reach the service?
    ///
    /// If true, requests with no `Authorization` header (or an invalid/expired JWT) will be proxied to the service (but will receive an `Anonymous: true` header)
    /// If false, they will be rejected (with a 401 response)
    pub allow_anonymous: bool,
    
    /// Should invalid/expired tokens be stripped from the upstream request?
    ///
    /// If true, invalid `Authorization` headers will be removed from the request.
    pub remove_invalid_tokens: bool,

    /// What JWT scopes are required for the service?
    /// 
    /// If the JWT does not contain the required scopes, the request will be rejected with a 401.
    pub required_scopes: Vec<String>,

    /// Are tokens in cookies supported?
    ///
    /// If true, CSRF protection is enabled and access tokens are extracted from cookies.
    pub cookies: bool,
}
```

This would be converted into configuration for the service proxy (currently Kongfig plugin entries).

Assuming #120 is done, this would be represented using the following source struct.

```rust
pub struct AuthorizationSource {
    /// Allows easy enabling/disabling at different levels.
    pub enabled: Option<bool>,
    pub configuration: Option<TemplatedString>,
    pub legacy: Option<bool>,
    /// Must be non-empty
    pub allowed_audiences: Option<Vec<String>>,
    pub allow_anonymous: Option<bool>,
    pub remove_invalid_tokens: Option<bool>,
    pub required_scopes: Option<Vec<String>>,
    pub cookies: bool,
}

/// Used in shipcat.conf
pub struct KongDefaults {
    pub auth: Option<Authentication>

    pub authorization: Option<AuthorizationSource>,
}

pub struct KongSource {
    /// ...

    /// If set explicitly, treated as `authorization.enabled: false`
    /// Post migration, this will be removed
    pub auth: Option<Authentication>

    pub authorization: Option<AuthorizationSource>,
}
```

# Possible Future Enhancements
* Authorization Permissions
    * Services could define the permissions they may require (which will be used to configuration the "authorization service")
