### ISSUE TITLE
Allow templating of kong.base_url in kong cors headers

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#147]
Currently there's quite a bit of duplication in kong configurations because the cors.origin urls are different per region/environment:

```yaml
kong:
  ...
  cors:
    ...
    origin: "https://svc1.x.babylontech.co.uk, https://sv2.x.babylontech.co.uk"
```

And as a consequence the entire thing is copied across multiple region override files.

Allow templating of cors.origin so that we can use:

```yaml
kong:
  ...
  cors:
    ...
    origin: "https://svc1.{kong.base_url}, https://sv2.{kong.base_url}"
```

and consequently move `kong` configuration up into environment files or the root manifest.

Maybe even allow origin to be a `Vec` so that it's a readable thing.
