### ISSUE TITLE
API URL template function

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#154]
Currently, if a service wants to use the HTTP API of another service and needs to know the URL of the service, it needs to build that URL itself (e.g., `MY_SERVICE_URL: '{{ base_urls.service }}/my-service/v1/'`).

This has the following issues:
* The actual dependencies of a service (as defined in the env vars) can become out of sync with the `dependencies` array.
* The dev needs to know the Kong mappings of the service.
* It's possible to depend on a service which isn't deployed in the current region.
* It's not possible to work out what the dependent services are of an API (e.g., is it safe to remove `v1` of an API).

# Proposal
## `api_url` function
Introduce an `api_url(name, version)` function to the `tera` templating context, which resolves to the full Kong URL of a service. This function would fail if the service or API version doesn't exist.

```yaml
# services/foo-service/shipcat.yml
env:
  MY_SERVICE_URL: "{{ api_url('my-service', 'v1') }}"
  # equivalent to 
  # MY_SERVICE_URL: "{{ base_urls.service }}/my-service/v1"

```

Introduce an `apis` object:

```yaml
# services/my-service/shipcat.yml
apis:
  v1:
    type: http
    kong:
      uris: '/my-service/v1'
  internal:
    type: grpc
```

# Possible enhancements
* Generate `dependencies` from usages of `api_url` (or just enforce that they are the same).
* Flag whether an API call needs to go via Kong or can go direct to pod (e.g., resolve to `https://my-service.dev.svc.cluster.local/v1` instead of the Kong URL)
