### ISSUE TITLE
Allow an `special` key for non-typechecked properties?

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#157]
An idea. Can potentially be used to make developing against non-standard charts easier.

e.g.

```yaml
name: somesvc
special:
  anything: goes
  here: 2
```

See [std::any](https://doc.rust-lang.org/std/any/trait.Any.html) might work, but don't think you can serialize/deserialize it. Might have to tell serde it's a json::Value or something similar.

Thoughts?
