### ISSUE TITLE
Use custom Vault path/key in environment variables

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#170]
Currently, the only way to load an environment variable from Vault is to use the `IN_VAULT` string, which loads the `value` key for the path of the same name.

This means it's hard for other tools to write a secret in a standardised form, they currently have to know the names of the service's environment variables (e.g., Platform Components needs to know the names of the DB environment variables and the Identity CLI needs to know the names of the OAuth 2 variables).

This also prevents tools from being restricted to only modifiying specific secrets using Vault policies (e.g., the Identity CLI should only be able to write to `secret/dev-uk/*/client_credentials`, with keys `client_id` and `client_secret`).

If an environment variable could read arbitrary secrets, these problems would be solved.

# Proposed Solution
```yaml
# services/foo/shipcat.yml (region = dev-uk)
env:
  # Option 1
  CLIENT_ID: "{{ secret('client_credentials').client_id }}" # reads secret/dev-uk/foo/client_credentials#client_id
  POSTGRES_NAME: "{{ secret('rds/DB_NAME').value }}" # reads secret/dev-uk/foo/rds/DB_NAME#value
  # Option 2
  CLIENT_SECRET: # reads secret/dev-uk/foo/client_credentials#client_secret
    secret:
      path: client_credentials
      key: client_secret
  POSTGRES_PASSWORD:  # reads secret/dev-uk/foo/rds/DB_PASSWORD#value
    secret:
      path: rds/DB_PASSWORD
```

I think Option 1 would be better from the perspective of a manifest author, as Option 2 has a lot of boilerplate.

Thoughts?
