### ISSUE TITLE
Codeowners not generated for team with only githubAdmin

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#184]
If you have the following setup:

```yaml
# shipcat.conf
teams:
- name: my-team
  githubAdmin: my-team-admins

# services/my-service/shipcat.yml
metadata:
  team: my-team
```

I'd expect `CODEOWNERS` to contain the following:

```
# CODEOWNERS
services/my-service/* @Organisation/my-team-admins
```

However, the entry for the service is only generated when there is at least one entry in the team's `owners` list.
