### ISSUE TITLE
Custom Helm values

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#213]
It'd be useful if custom values could be passed to Helm for templating. This would allow feature flags and gradual roll-out of K8s manifest changes, without needing to add lots of complicated `{{ if has .Values.region .Values.regionsWithFeatureX }}` templates.

# Proposal

Add a `helm_values: Map<String, serde_yaml::Value>` field to `Manifest`, which can be defined at any level (globally/region/service/overrides) and merged by key.

This will be exposed under the value `custom` to Helm.

## Example

```yaml
# shipcat.conf
region:
  - name: dev-uk
    defaults:
      helm_values:
        featureX: false
        featureY: "disabled"

# services/foo/manifest.yml
helm_values:
  featureX: true

# services/foo/dev-uk.yml
helm_values: 
  featureY: "enabled"
```

would result in the following:

```yaml
$ shipcat values foo --region=dev-uk
custom:
  featureX: true # from manifest.yml
  featureY: "enabled" # from dev-uk.yml
...

$ shipcat values foo --region=staging-uk
custom:
  featureX: true # from manifest.yml
...
```
