### ISSUE TITLE
Set environment variables on sidecars

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#31]
It would be useful if it was possible to set environment variables on sidecars from a service's manifest.

The values should be processed the same way as the main container's environment variables.

```yaml
sidecars:
- name: example-sidecar
  env:
    # Static value
    USERNAME: a-user
    # Value from Vault
    PASSWORD: IN_VAULT
    # Value from tera template
    URL: "{{ base_urls.services }}/oauth2/token"
```
