### ISSUE TITLE
Add support for Kong JWT auth plugin

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#60]
As part of IDM-61, we need to be able to configure Kong to accept/validate JWT access tokens, instead of tokens issued by Kong itself. We can do this using [the Kong JWT plugin](https://docs.konghq.com/hub/kong-inc/jwt/).

# Proposal
Alter `kong.rs`/`region.rs` to support/validate the following config:

```yaml
# shipcat.conf
regions:
- kong:
    jwt_consumers:
      my-consumer:
        issuer: https://my-issuer/
        public_key: >-
          -----BEGIN PUBLIC KEY-----
          ...
          -----END PUBLIC KEY-----

# services/my-service/shipcat.yml
kong:
  auth: jwt # Instead of oauth2 or "none"
  # Optional, same behaviour as with `oauth2`
  oauth2_anonymous: ...
```

which would be converted into the following kongfig:

```yaml
apis:
- plugins:
  - name: jwt
    attributes:
      config:
        uri_param_names: []
        claims_to_verify: [exp]
consumers:
  - username: my-consumer
    credentials:
      - name: jwt
        attributes:
          algorithm: RS256
          key: https://my-issuer/
          rsa_public_key: |-
            -----BEGIN PUBLIC KEY-----
            ...
            -----END PUBLIC KEY-----
```

Does this config seem sensible?
