### ISSUE TITLE
Per-environment manifest overrides

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#87]
For lots of services, the config doesn't vary across different regions in an environment (i.e., `prod-uk.yml` is the same as `prod-ca.yml`). As the number of regions increase, this will become more of a problem.

This could be solved by allowing a per-environment manifest override.

E.g., for a service in `prod-uk` (with `environment: prod` in the region definition), the following files are considered (highest to lowest precedence):
* `prod-uk.yml`
* `prod.yml`
* `shipcat.yml`

**Comment by clux** [comment]
That sounds sensible.

What happens if a service has all overrides?
3-way merge or drop the middle one?

**Comment by janslow** [comment]
I'd expect a 3-way merge. For example:

```yaml
# shipcat.yml
regions: [prod-uk, prod-sg]
env:
  FEATURE_A: enabled
  FEATURE_B: enabled

# prod.yml
version: 1.2.3
env:
  FEATURE_A: disabled
  FEATURE_B: disabled

# prod-uk.yml
env:
  FEATURE_A: enabled
```

Would be equivalent to
```yaml
# prod-uk.yml
version: 1.2.3
env:
  FEATURE_A: enabled
  FEATURE_B: disabled

# prod-sg.yml

version: 1.2.3
env:
  FEATURE_A: disabled
  FEATURE_B: disabled
```
